language: C++
sudo: required
dist: trusty

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-5
   - g++-5

before_install:
 - pip install --user cpp-coveralls

install:
 - sudo make package
script:
 - export CC=g++-5
 - export CXX=g++-5
 - make "CFLAGS=--coverage" "LDFLAGS=--coverage -lgcov"

after_success:
 - coveralls -b . --gcov gcov-5 --exclude libs --exclude test --gcov-options '\-lp' --exclude-lines-pattern BOOST_ASSERT
 
