language: C++
sudo: required
dist: xenial

addons:
 apt:
  packages:
   - gcc-5
   - g++-5

before_install:
 - pip install --user cpp-coveralls

install:
 - sudo make package

script:
 - export CC=g++-5
 - export CXX=g++-5
 - make coverage

after_success:
 - coveralls -b . --gcov gcov-5 --exclude libs --exclude src/test --gcov-options '\-lp' --exclude-lines-pattern BOOST_ASSERT --skip-ssl-verify
 - export CODECOV_TOKEN="a07eb55e-f756-40de-8b1f-c3c06bb78f0b"
 - bash <(curl -s https://codecov.io/bash)

