language: C++
sudo: required
dist: trusty

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-5
   - g++-5

install:
 - sudo make package
script:
 - export CC=g++-5
 - export CXX=g++-5
 - make

