name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: prepare coveralls
      run: pip install --user cpp-coveralls
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: make package
      run: sudo make package
    - name: make
      run: make coverage
    - name: send to coveralls
      run: coveralls -b src --exclude libs --exclude src/test --gcov-options '\-lp' --exclude-lines-pattern BOOST_ASSERT -t vqkCTuaT6CALS6yHvqMUFrplHcByvUmIx

