name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: prepare coveralls
      run: pip install --user cpp-coveralls
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: make package
      run: sudo make package
    - name: make
      run: make coverage
    - name: lcov
      run: lcov -c -d . -o lcov.info

